general {
    col.active_border = rgba(CDA8C4ff) rgba(5959A6ff) 45deg
    col.inactive_border = rgba(464044ff) rgba(7C5067ff) 45deg
}

group {
    col.border_active = rgba(464044ff) rgba(7C5067ff) 45deg
    col.border_inactive = rgba(2B2A31cc) rgba(392E5Dcc) 45deg
    col.border_locked_active = rgba(564751ff) rgba(694C5Cff) 45deg
    col.border_locked_inactive = rgba(2F2D3Ecc) rgba(342E4Dcc) 45deg
}
