# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Cursor
cursor_shape beam
cursor_trail 1

# No stupid close confirmation
confirm_os_window_close 0

# Use fish shell
shell fish

# Windows Terminal style tabs
map ctrl+t new_tab
map ctrl+w no_op
map ctrl+tab next_tab
map ctrl+shift+tab previous_tab

# Always show tab basr
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1

# Catppuccin theme
include catppuccin.conf

